config/routes.rb
Sep::Application.routes.draw do
  resources :codigos

  resources :assignments

  resources :roles

  resources :bitacoras

  resources :tipopracticas
  resources :evaluaciones



  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/index"
  get "users/show"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/destroy"
  root 'pages#home'
  get "pages/admin"
  get "pages/admin1"

 get "logout" => "sessions#destroy", :as => "logout"
 get "login" => "sessions#new", :as => "login"
 get "signup" => "users#new", :as => "signup"
 resources :users
 resources :sessions

  get "pages/home"
  get "home"  => "pages#home", :as => "home"
  get "admin"  => "pages#admin", :as => "admin"
  get "admin1"  => "pages#admin1", :as => "admin1"

 resources :tipo_factores do
    resources :factores
  end

  resources :estudiantes do
    resources :asignares_proy
  end
  resources :asignares_proy do 
    resources :actividades  
  end

 

  match '/about',   to: 'pages#about',   via: 'get'

  resources :novedades

  resources :empresas

  resources :detalle_evaluaciones

  

  resources :areas


 resources :actividades
  resources :fichas

  resources :programas

  resources :categorias

  resources :jefes

  resources :actestados

  resources :tipodocs

  resources :titulaciones

  resources :centros

  get "ventana_codigo"  => "evaluaciones#ventana_codigo", :as => "ventana_codigo"

  post "valida_codigo"  => "evaluaciones#valida_codigo", :as => "valida_codigo"


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
      user ||= User.new
      if user
       if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :jefe
        can :manage, [Evaluacion] if user.is? :jefe
      elsif user.has_role? :aprendiz
        can :manage, [Estudiante, Bitacora, Actividad, AsignarProy, User]
      elsif user.has_role? :directivo
        can :manage, [Estudiante, Empresa, Evaluacion, User, Jefe]
     elsif user.has_role? :monitor
        can :manage, :all
      end
    end
  end
end


   
 

app/models/actestado.rb
class Actestado < ActiveRecord::Base
  has_many :actividades
end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  belongs_to :categoria
  belongs_to :objsyproy
  belongs_to :asignar_proy
  belongs_to :actestado
  belongs_to :estudiante
  has_many :bitacoras
  def self.search(search)
    where("descripcion like '%#{search}%'")
  end
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :factores
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/bitacora.rb
class Bitacora < ActiveRecord::Base
  belongs_to :estudiante
  belongs_to :categoria
  belongs_to :actestado
  belongs_to :asignar_proy
  belongs_to :asignar_proy
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :actividades
  def self.search(search)
    where("nombre like '%#{search}%'")
  end
end

app/models/centro.rb
class Centro < ActiveRecord::Base
  has_many :programas
end

app/models/codigo.rb
class Codigo < ActiveRecord::Base
  belongs_to :estudiante
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :jefes
  def self.search(search)
    where("nombre like '%#{search}%' or nit like '%#{search}%'")
  end
end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  belongs_to :tipopractica
  belongs_to :ficha
  belongs_to :jefe
  belongs_to :tipodoc
  has_many :actividades
  has_many :asignares_proy
  has_many :evaluaciones
  has_many :bitacoras

  def self.search(search)
    where("nombre1 like '%#{search}%' or nombre2 like '%#{search}%'")
  end
end

app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  belongs_to :estudiante
  belongs_to :jefe


  has_many :detalle_evaluaciones
  def self.search(search)
    where("aspectospositivofactortecnico like '%#{search}%'")
  end
end

app/models/factor.rb
class Factor < ActiveRecord::Base
  belongs_to :area
  belongs_to :tipo_factor
  has_many :detalle_evaluaciones
  def self.search(search)
    where("nombre like '%#{search}%' or descripcion like '%#{search}%'")
  end
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  belongs_to :programa
  has_many :estudiantes
end

app/models/jefe.rb
class Jefe < ActiveRecord::Base
  belongs_to :empresa
  has_many :estudiantes
  has_many :evaluaciones
  has_many :tipodocs
  def self.search(search)
   where("nombres like '%#{search}%' or apellidos like '%#{search}%'")
  end
end

app/models/novedad.rb
class Novedad < ActiveRecord::Base
  belongs_to :user
  belongs_to :actestado
end

app/models/programa.rb
class Programa < ActiveRecord::Base
  belongs_to :centro
  belongs_to :titulacion
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :assignments
    has_many :users, :through => :assignments
end

app/models/tipodoc.rb
class Tipodoc < ActiveRecord::Base
  has_many :estudiantes
  belongs_to :jefe
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, :through => :assignments
  authenticates_with_sorcery!
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :username
  validates_uniqueness_of :username
  belongs_to :tipodoc
  def self.search(search)
    where("username like '%#{search}%'")
  end

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

end

app/controllers/factores_controller.rb
class FactoresController < ApplicationController
  before_action :set_factor, :require_login, only: [:show, :edit, :update, :destroy]
  before_filter :require_login
  before_filter :find_tipo_factor_factores
  
  def index
   
    if params[:registro] == nil or params[:registro] <= '0' then
        params[:registro] = 4
    end
    @factores = @tipo_factor.factores.search(params[:buscar]).page(params[:page]).per_page(params[:registro].to_i)  
  end

  def show
    @factor = Factor.find(params[:id])
  end

  def new
    @factor = Factor.new
  end

  def edit
    @factor = Factor.find(params[:id])
  end

  def create
    @factor = @tipo_factor.factores.build(factor_params)
    render :action => :new unless @factor.save
  end

  def update
    @factor = Factor.find(params[:id])
    render :action => :edit unless @factor.update_attributes(factor_params)
  end

  def destroy
    @factor = Factor.find(params[:id])
    @factor.destroy
  end

  private
  
  def find_tipo_factor_factores
    @tipo_factor = TipoFactor.find(params[:tipo_factor_id])
    @factor = Factor.find(params[:id]) if params[:id]
  end 

  private
   
  def set_factor
    @factor = Factor.find(params[:id])
  end

  def factor_params
    params.require(:factor).permit(:area_id, :tipo_factor_id, :descripcion, :nombre)
  end
end

app/helpers/factores_helper.rb
module FactoresHelper
end

app/views/factores/_factor.html.erb
<tr id=<%= "factor_#{factor.id}" %>>
	
	<td><%= factor.nombre %></td>
	<td><%= factor.area.nombre %></td>
	
	<td> 
      <%= link_to image_tag('Crud/mostrar.png'), tipo_factor_factor_path(@tipo_factor, factor), :remote => true, :rel => "tooltip", :title => "Mostrar", :class => 'btn btn-mini' %>
      <%= link_to image_tag('Crud/editar1.png'), edit_tipo_factor_factor_path(@tipo_factor, factor), :remote => true, :rel => "tooltip", :title => "Editar", :class => 'btn btn-mini'%>  
    </td>
</tr>

app/views/factores/_form.html.erb
<%= simple_form_for([@tipo_factor, @factor], :html => { :multipart => true, :remote => true }) do |f| %>
 <div class="user">
    <div class="modal-header">
      <a href="#" class="close"   onclick="$.lazybox.close()">&times;</a>
      <h4 class="modal-title"><h3>Datos Factores</h3></h4>
    </div><br>
      <div class="row">
        <div class="col-md-4">
          Nombre:
        </div>
        <div class="col-md-6">
          <%= f.input :nombre, :label => false,  :required => true  %>
        </div>
        <div class="col-md-4">
          Areas:
        </div>
        <div class="col-md-6">
          <%= f.collection_select :area_id , Area.all, :id, :nombre, :prompt => "Selecione Area", :label => false,  :required => true  %></br></br>
        </div>
        <div class="col-md-4">
          Descripción:
        </div>
        <div class="col-md-6">
          <%= f.input :descripcion, :label => false,  :required => true %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "guardar", :class => 'btn btn-primary' %>
        <a href="#" class="btn" onclick="$.lazybox.close()">Cerrar</a>
      </div>
  </div>
<% end %>

app/views/factores/_show.html.erb
<div class="modal-header">
  <button  class="close" onclick="$.lazybox.close()">&times;</button>
  <h3>Factores</h3>
</div>
  <div class="modal-body">
    <table class="table table-striped table-condensed">
      <tr>
        <td><b class="">ID: </b></td>
        <td><%= @factor.id %></td>
      </tr>
      <tr>
        <td><b class="">Nombres: </b></td>
        <td><%= @factor.nombre%></td>
      </tr>
      <tr>
        <td><b class="">Areas: </b></td>
        <td><%= @factor.area.nombre %></td>
      </tr>
      <tr>
        <td><b class="">Descripciónes: </b></td>
        <td><%= @factor.descripcion %></td>
      </tr>
    </table>
    <div class="modal-footer">
      <a onclick="$.lazybox.close()">&times;</a>
    </div>           
</div>

app/views/factores/create.js.erb
$('table tbody').append("<%= escape_javascript(render @factor) %>");
$.lazybox.close();

app/views/factores/destroy.js.erb
$("table tr#factor_<%= @factor.id %>").remove();

app/views/factores/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true, close: false, klass: 'sticker', fixed: true});

app/views/factores/index.html.erb
<div id="example" class="page-header">
    <h3>Datos Factores</h3>
    <div class="navbar">
    <div class="navbar-inner">
    <li id='buscar' class="brand" href="#">Buscar</li>
      <div class="row">
        <div class="span6">
          <form method="GET" class="form-inline" >
            <input id='buscar' name="buscar" class="search-query" type="text" placeholder="Buscar" >
            <button id='buscar' type="submit" class="btn btn-primary"><i class="icon-search icon-white"></i></button>
          </form>
        </div>
      </div>
    </div>
  </div>
 </div>
  <table class="table table-hover"  >
    <thead>
      <tr>
        <th >id</th>
        <th >NombreFactor</th>
        <th >Areas</th> 
        <th >Descripciones</th>
        <th >Acciones</th>          
      </tr>
    </thead>
    <tbody>
      <%= render @factores %>
    </tbody>
    <tfoot>
      <tr>
        <td>
          <td>
            <%= link_to image_tag('Crud/save.png'),  new_tipo_factor_factor_path,  :remote => true %>
          </td>
          <td><%= link_to image_tag("Crud/tipofactores.png"), tipo_factores_path,  :rel => "tooltip", :title => "Regresar TipoFactores", :class => "btn btn-mini"  %>
          </td>
          <td><%= link_to image_tag("Crud/admin.png"), admin_path,  :rel => "tooltip", :title => "Regresar Administración", :class => "btn btn-mini"  %></td>
          </td>
      </tr>
    </tfoot>
  </table>
  <div id="pagination">
    <ul class="pagination">
      <%= will_paginate @factores, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente&raquo;' %>
    </ul>
</div>

app/views/factores/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>", {close: false, klass: 'sticker', fixed: true});

app/views/factores/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/factores/update.js.erb
$('tr#factor_<%= @factor.id %>').replaceWith("<%= escape_javascript(render @factor) %>")
$.lazybox.close()