config/routes.rb
Sep::Application.routes.draw do
  resources :codigos

  resources :assignments

  resources :roles

  resources :bitacoras

  resources :tipopracticas
  resources :evaluaciones



  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/index"
  get "users/show"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/destroy"
  root 'pages#home'
  get "pages/admin"
  get "pages/admin1"

 get "logout" => "sessions#destroy", :as => "logout"
 get "login" => "sessions#new", :as => "login"
 get "signup" => "users#new", :as => "signup"
 resources :users
 resources :sessions

  get "pages/home"
  get "home"  => "pages#home", :as => "home"
  get "admin"  => "pages#admin", :as => "admin"
  get "admin1"  => "pages#admin1", :as => "admin1"

 resources :tipo_factores do
    resources :factores
  end

  resources :estudiantes do
    resources :asignares_proy
  end
  resources :asignares_proy do 
    resources :actividades  
  end

 

  match '/about',   to: 'pages#about',   via: 'get'

  resources :novedades

  resources :empresas

  resources :detalle_evaluaciones

  

  resources :areas


 resources :actividades
  resources :fichas

  resources :programas

  resources :categorias

  resources :jefes

  resources :actestados

  resources :tipodocs

  resources :titulaciones

  resources :centros

  get "ventana_codigo"  => "evaluaciones#ventana_codigo", :as => "ventana_codigo"

  post "valida_codigo"  => "evaluaciones#valida_codigo", :as => "valida_codigo"


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
      user ||= User.new
      if user
       if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :jefe
        can :manage, [Evaluacion] if user.is? :jefe
      elsif user.has_role? :aprendiz
        can :manage, [Estudiante, Bitacora, Actividad, AsignarProy, User]
      elsif user.has_role? :directivo
        can :manage, [Estudiante, Empresa, Evaluacion, User, Jefe]
     elsif user.has_role? :monitor
        can :manage, :all
      end
    end
  end
end


   
 

app/models/actestado.rb
class Actestado < ActiveRecord::Base
  has_many :actividades
end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  belongs_to :categoria
  belongs_to :objsyproy
  belongs_to :asignar_proy
  belongs_to :actestado
  belongs_to :estudiante
  has_many :bitacoras
  def self.search(search)
    where("descripcion like '%#{search}%'")
  end
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :factores
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/bitacora.rb
class Bitacora < ActiveRecord::Base
  belongs_to :estudiante
  belongs_to :categoria
  belongs_to :actestado
  belongs_to :asignar_proy
  belongs_to :asignar_proy
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :actividades
  def self.search(search)
    where("nombre like '%#{search}%'")
  end
end

app/models/centro.rb
class Centro < ActiveRecord::Base
  has_many :programas
end

app/models/codigo.rb
class Codigo < ActiveRecord::Base
  belongs_to :estudiante
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :jefes
  def self.search(search)
    where("nombre like '%#{search}%' or nit like '%#{search}%'")
  end
end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  belongs_to :tipopractica
  belongs_to :ficha
  belongs_to :jefe
  belongs_to :tipodoc
  has_many :actividades
  has_many :asignares_proy
  has_many :evaluaciones
  has_many :bitacoras

  def self.search(search)
    where("nombre1 like '%#{search}%' or nombre2 like '%#{search}%'")
  end
end

app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  belongs_to :estudiante
  belongs_to :jefe


  has_many :detalle_evaluaciones
  def self.search(search)
    where("aspectospositivofactortecnico like '%#{search}%'")
  end
end

app/models/factor.rb
class Factor < ActiveRecord::Base
  belongs_to :area
  belongs_to :tipo_factor
  has_many :detalle_evaluaciones
  def self.search(search)
    where("nombre like '%#{search}%' or descripcion like '%#{search}%'")
  end
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  belongs_to :programa
  has_many :estudiantes
end

app/models/jefe.rb
class Jefe < ActiveRecord::Base
  belongs_to :empresa
  has_many :estudiantes
  has_many :evaluaciones
  has_many :tipodocs
  def self.search(search)
   where("nombres like '%#{search}%' or apellidos like '%#{search}%'")
  end
end

app/models/novedad.rb
class Novedad < ActiveRecord::Base
  belongs_to :user
  belongs_to :actestado
end

app/models/programa.rb
class Programa < ActiveRecord::Base
  belongs_to :centro
  belongs_to :titulacion
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :assignments
    has_many :users, :through => :assignments
end

app/models/tipodoc.rb
class Tipodoc < ActiveRecord::Base
  has_many :estudiantes
  belongs_to :jefe
end

app/models/titulacion.rb
class Titulacion < ActiveRecord::Base
  has_many :programas
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, :through => :assignments
  authenticates_with_sorcery!
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :username
  validates_uniqueness_of :username
  belongs_to :tipodoc
  def self.search(search)
    where("username like '%#{search}%'")
  end

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

end

app/controllers/tipodocs_controller.rb
class TipodocsController < ApplicationController
  before_action :set_tipodoc, :require_login, only: [:show, :edit, :update, :destroy]
  before_filter :require_login
  
  def index
    
    @tipodocs = Tipodoc.all
  end

  def show
    @tipodoc = Tipodoc.find(params[:id]) 
  end

  def new
    @tipodoc = Tipodoc.new
  end

  def edit
    @tipodoc = Tipodoc.find(params[:id]) 
  end

  def create
    @tipodoc = Tipodoc.new(tipodoc_params)
    render :action => :new unless @tipodoc.save
  end

  def update
    @tipodoc = Tipodoc.find(params[:id])
    render :action => :edit unless @tipodoc.update_attributes(tipodoc_params)
  end

  def destroy
   @tipodoc = Tipodoc.find(params[:id])
   @tipodoc.destroy
  end

  private

  def set_tipodoc
    @tipodoc = Tipodoc.find(params[:id])
  end

  def tipodoc_params
    params.require(:tipodoc).permit(:descripcion, :sigla)
  end
end

app/helpers/tipodocs_helper.rb
module TipodocsHelper
end

app/views/tipodocs/_form.html.erb
<%= simple_form_for(@tipodoc, :html => { :multipart => true, :remote => true }) do |f| %>
   <div class="user">
      <div class="modal-header">
         <a href="#" class="close"   onclick="$.lazybox.close()">&times;</a>
        <h4 class="modal-title"><h3>Datos TipoDocumentos</h3></h4>
      </div><br>
        <div class="row">
          <div class="col-md-4">
            Siglas:
          </div>
        <div class="col-md-6">
          <%= f.input :sigla, :label => false,  :required => true %>
        </div>
        <div class="col-md-4">
          Descripciónes:
        </div>
        <div class="col-md-6">
          <%= f.input :descripcion, :label => false,  :required => true  %>
        </div>
      </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <a href="#" class="btn" onclick="$.lazybox.close()">Cerrar</a>
  </div>
<% end %>

app/views/tipodocs/_show.html.erb
<div class="modal-header">
  <button  class="close" onclick="$.lazybox.close()">&times;</button>
  <h3>TipoDocumentos</h3>
</div>
  <div class="modal-body">
    <table class="table table-striped table-condensed">
      <tr>
        <td><b class="pull-right">ID: </b></td>
        <td><%= @tipodoc.id %></td>
      </tr>
      <tr>
        <td><b class="pull-right">Sigla: </b></td>
        <td><%= @tipodoc.sigla %></td>
      </tr>
      <tr>
        <td><b class="pull-right">Descripciones: </b></td>
        <td><%= @tipodoc.descripcion %></td>
      </tr>
    </table>
    <div class="modal-footer">
      <a onclick="$.lazybox.close()">&times;</a>
    </div>           
</div>

app/views/tipodocs/_tipodoc.html.erb
<tr id=<%= "tipodoc_#{tipodoc.id}" %>>
	<td><%= tipodoc.id %></td>
	<td><%= tipodoc.sigla %></td>
	<td><%= tipodoc.descripcion %></td>
	<td> 
		<%= link_to  image_tag('Crud/mostrar.png'), tipodoc, :remote => true, :class => 'btn btn-mini' %>
        <%= link_to image_tag('Crud/editar1.png', :title => "Editar Equipos"), edit_tipodoc_path(tipodoc), :remote => true,
          :class => 'btn btn-mini'%>
	</td>
</tr>

app/views/tipodocs/create.js.erb
$('table tbody').append("<%= escape_javascript(render @tipodoc) %>");
$.lazybox.close();

app/views/tipodocs/destroy.js.erb
$("table tr#tipodoc_<%= @tipodoc.id %>").remove();

app/views/tipodocs/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true, close: false, klass: 'sticker', fixed: true});

app/views/tipodocs/index.html.erb
<h3>Datos TipoDocumentos</h3>
  <table class="table table-hover"  >
    <thead>
      <tr>
        <th >id</th>
        <th >Siglas</th>
        <th >Descripciones</th> 
        <th >Acciones</th>      
      </tr>
    </thead>
    <tbody>
      <%= render @tipodocs %>
    </tbody>
    <tfoot>
      <tr>
        <td>
          <%= link_to image_tag('Crud/save.png'),  new_tipodoc_path,  :remote => true %>
        </td>
      </tr>
    </tfoot>
  </table>
      

app/views/tipodocs/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>", {close: false, klass: 'sticker', fixed: true});

app/views/tipodocs/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/tipodocs/update.js.erb
$('tr#tipodoc_<%= @tipodoc.id %>').replaceWith("<%= escape_javascript(render @tipodoc) %>")
$.lazybox.close()