config/routes.rb
Sep::Application.routes.draw do
  resources :codigos

  resources :assignments

  resources :roles

  resources :bitacoras

  resources :tipopracticas
  resources :evaluaciones



  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/index"
  get "users/show"
  get "users/new"
  get "users/create"
  get "users/edit"
  get "users/update"
  get "users/destroy"
  root 'pages#home'
  get "pages/admin"
  get "pages/admin1"

 get "logout" => "sessions#destroy", :as => "logout"
 get "login" => "sessions#new", :as => "login"
 get "signup" => "users#new", :as => "signup"
 resources :users
 resources :sessions

  get "pages/home"
  get "home"  => "pages#home", :as => "home"
  get "admin"  => "pages#admin", :as => "admin"
  get "admin1"  => "pages#admin1", :as => "admin1"

 resources :tipo_factores do
    resources :factores
  end

  resources :estudiantes do
    resources :asignares_proy
  end
  resources :asignares_proy do 
    resources :actividades  
  end

 

  match '/about',   to: 'pages#about',   via: 'get'

  resources :novedades

  resources :empresas

  resources :detalle_evaluaciones

  

  resources :areas


 resources :actividades
  resources :fichas

  resources :programas

  resources :categorias

  resources :jefes

  resources :actestados

  resources :tipodocs

  resources :titulaciones

  resources :centros

  get "ventana_codigo"  => "evaluaciones#ventana_codigo", :as => "ventana_codigo"

  post "valida_codigo"  => "evaluaciones#valida_codigo", :as => "valida_codigo"


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
      user ||= User.new
      if user
       if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :jefe
        can :manage, [Evaluacion] if user.is? :jefe
      elsif user.has_role? :aprendiz
        can :manage, [Estudiante, Bitacora, Actividad, AsignarProy, User]
      elsif user.has_role? :directivo
        can :manage, [Estudiante, Empresa, Evaluacion, User, Jefe]
     elsif user.has_role? :monitor
        can :manage, :all
      end
    end
  end
end


   
 

app/models/actestado.rb
class Actestado < ActiveRecord::Base
  has_many :actividades
end

app/models/actividad.rb
class Actividad < ActiveRecord::Base
  belongs_to :categoria
  belongs_to :objsyproy
  belongs_to :asignar_proy
  belongs_to :actestado
  belongs_to :estudiante
  has_many :bitacoras
  def self.search(search)
    where("descripcion like '%#{search}%'")
  end
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :factores
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/bitacora.rb
class Bitacora < ActiveRecord::Base
  belongs_to :estudiante
  belongs_to :categoria
  belongs_to :actestado
  belongs_to :asignar_proy
  belongs_to :asignar_proy
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  has_many :actividades
  def self.search(search)
    where("nombre like '%#{search}%'")
  end
end

app/models/centro.rb
class Centro < ActiveRecord::Base
  has_many :programas
end

app/models/codigo.rb
class Codigo < ActiveRecord::Base
  belongs_to :estudiante
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :jefes
  def self.search(search)
    where("nombre like '%#{search}%' or nit like '%#{search}%'")
  end
end

app/models/estudiante.rb
class Estudiante < ActiveRecord::Base
  belongs_to :tipopractica
  belongs_to :ficha
  belongs_to :jefe
  belongs_to :tipodoc
  has_many :actividades
  has_many :asignares_proy
  has_many :evaluaciones
  has_many :bitacoras

  def self.search(search)
    where("nombre1 like '%#{search}%' or nombre2 like '%#{search}%'")
  end
end

app/models/evaluacion.rb
class Evaluacion < ActiveRecord::Base
  belongs_to :estudiante
  belongs_to :jefe


  has_many :detalle_evaluaciones
  def self.search(search)
    where("aspectospositivofactortecnico like '%#{search}%'")
  end
end

app/models/factor.rb
class Factor < ActiveRecord::Base
  belongs_to :area
  belongs_to :tipo_factor
  has_many :detalle_evaluaciones
  def self.search(search)
    where("nombre like '%#{search}%' or descripcion like '%#{search}%'")
  end
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  belongs_to :programa
  has_many :estudiantes
end

app/models/jefe.rb
class Jefe < ActiveRecord::Base
  belongs_to :empresa
  has_many :estudiantes
  has_many :evaluaciones
  has_many :tipodocs
  def self.search(search)
   where("nombres like '%#{search}%' or apellidos like '%#{search}%'")
  end
end

app/models/novedad.rb
class Novedad < ActiveRecord::Base
  belongs_to :user
  belongs_to :actestado
end

app/models/programa.rb
class Programa < ActiveRecord::Base
  belongs_to :centro
  belongs_to :titulacion
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :assignments
    has_many :users, :through => :assignments
end

app/models/tipodoc.rb
class Tipodoc < ActiveRecord::Base
  has_many :estudiantes
  belongs_to :jefe
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, :through => :assignments
  authenticates_with_sorcery!
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :username
  validates_uniqueness_of :username
  belongs_to :tipodoc
  def self.search(search)
    where("username like '%#{search}%'")
  end

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

end

app/controllers/actividades_controller.rb
class ActividadesController < ApplicationController
  before_action :set_actividad, only: [:show, :edit, :update, :destroy]
  before_filter :require_login
  before_filter :find_actividad_asignares_proy
 
  
  def index
    if params[:registro] == nil or params[:registro] <= '0' then
        params[:registro] = 4
    end
    @actividades = @asignar_proy.actividades.search(params[:buscar]).page(params[:page]).per_page(params[:registro].to_i)
  end

  def show
    @actividad = Actividad.find(params[:id])
  end

  def new
    @actividad = Actividad.new
  end

  def edit
    @actividad = Actividad.find(params[:id])
  end

  def create
    @actividad = @asignar_proy.actividades.build(actividad_params)
    render :action => :new unless @actividad.save 
  end

  def update
    @actividad = Actividad.find(params[:id])
    render :action => :edit unless @actividad.update_attributes(actividad_params)
  end

  def destroy
   @actividad = Actividad.find(params[:id])
   @actividad.destroy
  end
   private
  
  def find_actividad_asignares_proy
    @asignar_proy = AsignarProy.find(params[:asignar_proy_id])
    @actividad = Actividad.find(params[:id]) if params[:id]
  end 
  private
  
  def set_actividad
    @actividad = Actividad.find(params[:id])
  end

  def actividad_params
    params.require(:actividad).permit(:nombre, :estudiante_id, :fecha_inicio,
     :fecha_fin, :descripcion, :objetivo, :categoria_id, :objsyproy_id,
     :asignar_proy_id, :actestado_id, :actividad1, :actividad2, :actividad3,
     :actividad4, :actividad5)
  end
end

app/helpers/actividades_helper.rb
module ActividadesHelper
end

app/views/actividades/_actividad.html.erb
<tr id=<%= "actividad_#{actividad.id}" %>>
   <td><%= actividad.fecha_inicio %></td>
   <td><%= actividad.nombre %></td>
   <td><%= actividad.categoria.nombre %></td>
   <td><%= actividad.actestado.nombre %></td>
   <td><%= actividad.objetivo %></td>
   <td><%= actividad.fecha_fin %></td>
    <td> 
	  <%= link_to  image_tag('Crud/mostrar.png'), asignar_proy_actividad_path(@asignar_proy, actividad), :remote => true, :class => 'btn btn-mini' %>
      <%= link_to image_tag('Crud/editar1.png', :title => "Editar Equipos"), edit_asignar_proy_actividad_path(@asignar_proy, actividad), :remote => true, :class => 'btn btn-mini'%>
	</td>
</tr>

app/views/actividades/_form.html.erb
<%= javascript_include_tag "fecha" %>
<%= simple_form_for([@asignar_proy, @actividad], :html => { :multipart => true, :remote => true }) do |f| %>
<div class="user">
    <div class="modal-header">
      <a href="#" class="close"   onclick="$.lazybox.close()">&times;</a>
      <h4 class="modal-title"><h3>Datos Actvidades</h3></h4>
    </div><br>
    <div class="row">
      <div class="col-md-4">
        FechaInicio:
      </div>
      <div class="col-md-8">
        <%= f.input :fecha_inicio, :as => :string, :label => false, :required => true,  :input_html => {  :class => "datepicker " } %>
      </div>
      <div class="col-md-4">
        NombreAct:
      </div>
      <div class="col-md-8">
        <%= f.input :nombre, :label => false,  :required => true  %>
      </div>
       <div class="col-md-4">
        NombreAct1:
      </div>
      <div class="col-md-8">
        <%= f.input :actividad1, :label => false,  :required => true  %>
      </div>
       <div class="col-md-4">
        NombreAct2:
      </div>
      <div class="col-md-8">
        <%= f.input :actividad2, :label => false,  :required => true  %>
      </div>
       <div class="col-md-4">
        NombreAct3:
      </div>
      <div class="col-md-8">
        <%= f.input :actividad3, :label => false,  :required => true  %>
      </div>
       <div class="col-md-4">
        NombreAct4:
      </div>
      <div class="col-md-8">
        <%= f.input :actividad4, :label => false,  :required => true  %>
      </div>
       <div class="col-md-4">
        NombreAct5:
      </div>
      <div class="col-md-8">
        <%= f.input :actividad5, :label => false,  :required => true  %>
      </div>
      <div class="col-md-4">
        Categorias:
      </div>
      <div class="col-md-8">
        <%= f.collection_select :categoria_id, Categoria.all, :id, :nombre, :prompt => "Selecione Categoria" %><br><br>
      </div>
      <div class="col-md-4">
        EstEstado:
      </div>
      <div class="col-md-8">
        <%= f.collection_select :actestado_id , Actestado.all, :id, :nombre, :prompt => "Selecione ActEstado" %> <br><br> 
      </div>
      <div class="col-md-4">
        Descripción:
      </div>
      <div class="col-md-8">
        <%= f.input :descripcion, :label => false,  :required => true  %>
      </div>
      <div class="col-md-4">
        Objetivo:
      </div>
      <div class="col-md-8">
        <%= f.input :objetivo, :label => false,  :required => true  %>
      </div>
      <div class="col-md-4">
        FechaFin:
      </div>
      <div class="col-md-8">
        <%= f.input :fecha_fin, :as => :string, :label => false,  :required => true,  :input_html => {  :class => "datepicker" } %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.submit "guardar", :class => 'btn btn-primary' %>
    <a href="#" class="btn" onclick="$.lazybox.close()">Cerrar</a>
  </div>
<% end %>

app/views/actividades/_show.html.erb
<div class="modal-header">
  <button  class="close" onclick="$.lazybox.close()">&times;</button>
  <h3>Actividades</h3>
</div>
<div class="modal-body">
  <table class="table table-striped table-condensed">
    <tr>
      <td><b class="pull-right">ID: </b></td>
      <td><%= @actividad.id %></td>
    </tr>
    <tr>
      <td><b class="pull-right">FechaInicio: </b></td>
      <td><%= @actividad.fecha_inicio %></td>
    </tr>
      <tr>
      <td><b class="pull-right">NombreActividad: </b></td>
      <td><%= @actividad.nombre %></td>
    </tr>
    <tr>
      <td><b class="pull-right">ActualEstado: </b></td>
      <td><%= @actividad.actestado.nombre %></td>
    </tr>
      <tr>
      <td><b class="pull-right">Descripción: </b></td>
      <td><%= @actividad.descripcion %></td>
    </tr>
    <tr>
      <td><b class="pull-right">Objetivo: </b></td>
      <td><%= @actividad.objetivo %></td>
    </tr>
      <tr>
      <td><b class="pull-right">FechaFin: </b></td>
      <td><%= @actividad.fecha_fin %></td>
    </tr>
  </table>
  <div class="modal-footer">
    <a onclick="$.lazybox.close()">&times;</a>
  </div>           
</div>

app/views/actividades/create.js.erb
$('table tbody').append("<%= escape_javascript(render @actividad) %>");
$.lazybox.close();

app/views/actividades/destroy.js.erb
$("table tr#actividad_<%= @actividad.id %>").remove();

app/views/actividades/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {niceClose: true, close: false, klass: 'sticker', fixed: true});

app/views/actividades/index.html.erb
<div id="example" class="page-header">
  <h3>Actividades</h3>
  <div class="navbar">
    <div class="navbar-inner">
      <li id='buscar' class="brand" href="#">Buscar</li>
        <div class="row">
          <div class="span6">
            <form method="GET" class="form-inline" >
              <input id='buscar' name="buscar" class="search-query" type="text" placeholder="Buscar" >
              <button id='buscar' type="submit" class="btn btn-primary"><i class="icon-search icon-white"></i></button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <table class="table table-hover"  >
    <thead>
      <tr>
        <th >FechaInicio</th>
        <th >Nombre</th>
        <th >Categoria</th>
        <th >EstActual</th>
        <th >Objetivo</th>
        <th >FechaFin</th>
        <th >Acciones</th>      
      </tr>
    </thead>
    <tbody><%= render @actividades %></tbody>
    <tfoot>
      <tr>
        <td>
          <%= link_to image_tag('Crud/save.png'),  new_asignar_proy_actividad_path, :remote => true %>
        </td>
        <td><%= link_to image_tag("Crud/estudiantes.png"), estudiantes_path,  :rel => "tooltip", :title => "Regresar Estudiantes", :class => "btn btn-mini"  %>
        </td>
        <td><%= link_to image_tag("Crud/admin.png"), admin_path,  :rel => "tooltip", :title => "Regresar Administración", :class => "btn btn-mini"  %>
        </td>
      </tr>
    </tfoot>
  </table>
  <div id="pagination">
    <ul class="pagination">
      <%= will_paginate @actividades, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente&raquo;' %>
    </ul>
  </div>

      

app/views/actividades/new.js.erb
$.lazybox("<%= escape_javascript(render :partial => 'form') %>", {close: false, klass: 'sticker', fixed: true});

app/views/actividades/show.js.erb
$.lazybox("<%= j(render 'show') %>", {closeImg: true, klass: 'sticker', fixed: true})

app/views/actividades/update.js.erb
$('tr#actividad_<%= @actividad.id %>').replaceWith("<%= escape_javascript(render @actividad) %>")
$.lazybox.close()